-- Provinces data
DELETE FROM provinces WHERE id IN ('11','12','13','14','15','16','17','18','19','21','31','32','33','34','35','36','51','52','53','61','62','63','64','65','71','72','73','74','75','76','81','82','91','94');
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('11', 'ACEH', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('12', 'SUMATERA UTARA', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('13', 'SUMATERA BARAT', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('14', 'RIAU', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('15', 'JAMBI', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('16', 'SUMATERA SELATAN', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('17', 'BENGKULU', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('18', 'LAMPUNG', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('19', 'KEPULAUAN BANGKA BELITUNG', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('21', 'KEPULAUAN RIAU', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('31', 'DKI JAKARTA', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('32', 'JAWA BARAT', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('33', 'JAWA TENGAH', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('34', 'DI YOGYAKARTA', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('35', 'JAWA TIMUR', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('36', 'BANTEN', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('51', 'BALI', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('52', 'NUSA TENGGARA BARAT', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('53', 'NUSA TENGGARA TIMUR', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('61', 'KALIMANTAN BARAT', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('62', 'KALIMANTAN TENGAH', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('63', 'KALIMANTAN SELATAN', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('64', 'KALIMANTAN TIMUR', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('65', 'KALIMANTAN UTARA', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('71', 'SULAWESI UTARA', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('72', 'SULAWESI TENGAH', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('73', 'SULAWESI SELATAN', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('74', 'SULAWESI TENGGARA', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('75', 'GORONTALO', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('76', 'SULAWESI BARAT', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('81', 'MALUKU', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('82', 'MALUKU UTARA', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('91', 'PAPUA BARAT', NOW(), NOW());
INSERT INTO provinces (id, name, created_at, updated_at) VALUES ('94', 'PAPUA', NOW(), NOW());
